### ISSUE TITLE
add past board info

### ISSUE THREAD

**Issue by ejhumphrey** [ismir/ismir-home#11]
Should be added to the [about page](https://github.com/ismir/ismir-home/blob/master/docs/pages/about.md)

Officers (2018-2019)
President: Emilia Gómez, Universitat Pompeu Fabra, Spain
President-elect: Meinard Müller, International Audio Laboratories
Secretary: Eric J. Humphrey, Spotify, USA
Treasurer: Bob Sturm, KTH, Sweden
Member-at-large: Geoffroy Peeters, IRCAM, France
Member-at-large: Blair Kaneshiro, Smule, USA
Member-at-large: Douglas Turnbull, Ithaca College, USA
Student member: Iris Yuping Ren, Utrecht U., Netherlands

Officers (2016-2017)
President: Fabien Gouyon, Pandora, USA
President-elect: Emilia Gómez, Universitat Pompeu Fabra, Barcelona
Secretary: Eric J. Humphrey, Spotify, USA
Treasurer: Xiao Hu, University of Hong Kong, China
Member-at-large: Amélie Anglade, Germany
Member-at-large: Meinard Müller, International Audio Laboratories 
Erlangen, Germany
Member-at-large: Geoffroy Peeters, IRCAM, France
Student member: Andy Sarroff, Dartmouth, USA

Officers (2014-2015)
President: Simon Dixon, Queen Mary University of London, UK
...

Officers (2012-2013)
President: Tim Crawford, Goldsmiths University of London, UK
Secretary: Jin Ha Lee, University of Washington, USA
Treasurer: Xiao Hu, University of Denver, USA 
(http://hub.hku.hk/cris/rp/rp01711)
President-elect: Simon Dixon, Queen Mary University of London, UK
Member-at-large: J. Stephen Downie, University of Illinois at 
Urbana-Champaign, USA
Member-at-large: Meinard Mueller, Max-Planck-Institut für Informatik, 
Germany
Member-at-large: Frans Wiering, Universiteit Utrecht, The Netherlands
Student member: Eric J. Humphrey, PhD Candidate (ABD), MARL@NYU
Member-at-large: Emilia Gomez
Member-at-large: Fabien Gouyon
Member-at-large: Anja Volk

Officers (2010-2011)
President: J. Stephen Downie, University of Illinois at 
Urbana-Champaign, USA

**Comment by ajaysmurthy** [comment]
I see this info is already present in about page. Closing this for now.
