### ISSUE TITLE
Update conference dates

### ISSUE THREAD

**Issue by ejhumphrey** [ismir/ismir-home#27]
The homepage information is currently out of date. 

![image](https://user-images.githubusercontent.com/926379/73033442-00ada400-3e10-11ea-9fa8-338bb72ce46d.png)

Lines 8:10 in [index.md](https://github.com/ismir/ismir-home/blob/master/docs/index.md) should be updated with the correct information:
- 2019 removed
- 2020 updated with website URL

**Comment by audreylaplante** [comment]
Done!
