### ISSUE TITLE
Permanent home for reviewer guidelines?

### ISSUE THREAD

**Issue by bmcfee** [ismir/ismir-home#29]
In preparing for ISMIR 2020 reviewing, we noticed that the reviewer guidelines page (eg https://ismir2019.ewi.tudelft.nl/?q=guidelines-reviewers ) has been living at each conference's home page (if anywhere).

What do you think about providing a permanent home for this document on ismir.net, that can be revised each year by the PC as needed?  I'm happy to start a PR for this if folks like the idea.  We will need a quick turnaround on this though, since it could hold up the email blast to reviewers.

**Comment by ejhumphrey** [comment]
make it happen, we can get this through by EOD

**Comment by bmcfee** [comment]
Ok, will do once this call is over. Thanks for the quick response!
