### ISSUE TITLE
Links to conferences are broken

### ISSUE THREAD

**Issue by hendriks73** [ismir/ismir-home#37]
The [links to the individual conferences](http://ismir.net/conferences/) are broken.
They point to, for example, https://ismir2020.ismir.net/, which leads nowhere.
When instead going to http://ismir2020.ismir.net/ (via HTTP, not HTTPS), the redirect/s to the actual site succeeds.

Smells like a ISP/DNS configuration issue. I'd be happy to look into it, but lack permissions etc.

**Comment by hendriks73** [comment]
In the same go, one could probably fix #19

**Comment by ecanoc** [comment]
@ajaysmurthy  @audreylaplante, could this be related to the latest modifications on the site?

**Comment by ajaysmurthy** [comment]
@hendriks73 I tried to fix this issue, but could not. It is a DNS issue as you mentioned. Any pointers ? I have access to DNS settings and can make changes you suggest

**Comment by ajaysmurthy** [comment]
Thanks @hendriks73 for the pointers. This issue is now fixed.

**Comment by hendriks73** [comment]
Did you end up simply re-configuring the CNAME entry?

**Comment by ajaysmurthy** [comment]
I removed the subdomain forwarding ismir2021.ismir.net -> ismir2020.net and added a CNAME record that points the subdomain ismir2021.ismir.net -> ismir.net so that the ISMIR 2021 website is served from the hosting archive.
