### ISSUE TITLE
Deployment Pipeline not working

### ISSUE THREAD

**Issue by stefan-balke** [ismir/ismir-home#50]
Seems that the deployment pipeline is broken.
@ajaysmurthy any thoughts on this? You have access to the Webserver, don't you?

**Comment by stefan-balke** [comment]
Also it's no longer Travis CI but GitHub actions.
Maybe we have to redo the deployment scripts:
https://jekyllrb.com/docs/continuous-integration/github-actions/

**Comment by ajaysmurthy** [comment]
@stefan-balke Aware of this issue, but did not get a chance to look into and fix it yet. The webserver hosting the pages seems to be fine. As you suggest, we might have to redo deployment scripts.

**Comment by stefan-balke** [comment]
Thanks, no worries. Maybe you could render locally and deploy the current version in the meantime. All just minor changes.

**Comment by stefan-balke** [comment]
Any news on this? As said, manual push would be necessary to get the latest changes online.

**Comment by ajaysmurthy** [comment]
@stefan-balke I was able to build it locally (and test it on localhost), but I am facing some issues with manual push. Have you done this before?

**Comment by stefan-balke** [comment]
Hey, for now, just build it locally and push it via FTP to the server. Shouldn't that work?

**Comment by stefan-balke** [comment]
Any news on this @ajaysmurthy? We could also schedule a call for this.

**Comment by ajaysmurthy** [comment]
I tried building it locally - it build fine, but looks like it needs some changes to deploy it on the server. The tech volunteer team could not figure it out. @stefan-balke Happy to get on a call to discuss this? Will email you to set this up.

**Comment by ajaysmurthy** [comment]
@alastair helped resolve this issue.
