### ISSUE TITLE
Membership still links to softconf conference manager

### ISSUE THREAD

**Issue by bmcfee** [ismir/ismir-home#55]
I'm not sure if this is an error, but it seems wrong since ISMIR moved to CMT.  Does this link still work?

https://github.com/ismir/ismir-home/blob/0078282ea8ebf17a7e425a7b52469ada565b510b/docs/pages/membership.md?plain=1#L16-L21

**Comment by ajaysmurthy** [comment]
ISMIR paper management has moved to CMT, however we can still use the above link to become members of the society.
